spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sawdb
      authentication-database: admin

logging:
  level:
    org:
      hibernate: ERROR
      security: DEBUG

server:
  servlet:
    context-path: /api

jwt:
  secret:
    key: ${JWT_SECRET:my-secret-key}