spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/test

logging:
  level:
    org:
      hibernate: ERROR
      security: DEBUG

server:
  servlet:
    context-path: /api

jwt:
  secret:
    key: ${JWT_SECRET:my-secret-key}