version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: saw-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  saw:
    build: ../app/.
    container_name: spring-boot
    restart: always
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_HOST: localhost
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: test
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
    ports:
      - "8080:8080"

volumes:
  mongodb_data: